// src/angular/ImageCropper.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { lumina } from '../index.js';
import { LuminaCanvasComponent } from './LuminaCanvas.component';
import {
  CropArea,
  ImageAreaSelectorComponent,
} from './ImageAreaSelector.component';
import { type LuminaSource } from './types.js';

export type ImageCropperOutput = Blob | string;

@Component({
  selector: 'lumina-image-cropper',
  standalone: true,
  imports: [CommonModule, ImageAreaSelectorComponent, LuminaCanvasComponent],
  template: `
    <div class="lumina-image-cropper" [ngStyle]="containerStyle">
      <div
        class="crop-frame"
        [style.max-width.px]="maxWidth"
        [style.max-height.px]="maxHeight"
      >
        @if (appliedPreviewSrc) {
          <lumina-canvas
            [source]="appliedPreviewSrc"
            [canvasStyle]="{ width: '100%', height: '100%', display: 'block' }"
            (processError)="processError.emit($event)"
          ></lumina-canvas>
        } @else if (imageSrc) {
          <lumina-image-area-selector
            #selector
            [src]="imageSrc"
            [aspect]="aspectRatio"
            [lineColor]="lineColor"
            [overlayOpacity]="overlayOpacity"
            [showControls]="true"
            (cropChange)="handleCropChange($event)"
            (cropComplete)="handleCropComplete($event)"
          >
            <div luminaAreaControls class="crop-actions">
              <button
                type="button"
                class="apply"
                [disabled]="isCropping"
                (click)="applyCrop()"
              >
                {{ isCropping ? 'Processing...' : 'Apply Crop' }}
              </button>

              @if (allowReset) {
                <button
                  type="button"
                  class="reset"
                  [disabled]="isCropping"
                  (click)="reset()"
                >
                  Reset
                </button>
              }
            </div>
          </lumina-image-area-selector>
        }

        @if (isCropping) {
          <div class="processing">Processing...</div>
        }

        @if (allowReset && appliedPreviewSrc && !isCropping) {
          <div class="preview-actions" [ngClass]="buttonPosition">
            <button type="button" class="reset" (click)="reset()">Reset</button>
          </div>
        }
      </div>
    </div>
  `,
  styles: [
    `
      .lumina-image-cropper {
        padding: 16px;
        border-radius: 8px;
      }

      .crop-frame {
        position: relative;
        overflow: hidden;
        border: 1px solid #d8dde6;
        border-radius: 6px;
        background: #f6f7f9;
      }

      .crop-actions,
      .preview-actions {
        display: flex;
        gap: 8px;
        align-items: center;
      }

      .preview-actions {
        position: absolute;
        z-index: 1001;
      }

      .top-left {
        top: 12px;
        left: 12px;
      }

      .top-right {
        top: 12px;
        right: 12px;
      }

      .top-center {
        top: 12px;
        left: 50%;
        transform: translateX(-50%);
      }

      .bottom-left {
        bottom: 12px;
        left: 12px;
      }

      .bottom-center {
        bottom: 12px;
        left: 50%;
        transform: translateX(-50%);
      }

      .bottom-right {
        right: 12px;
        bottom: 12px;
      }

      button {
        min-height: 36px;
        padding: 0 12px;
        border: 1px solid #c9d2df;
        border-radius: 4px;
        background: #ffffff;
        color: #17202a;
        font: inherit;
        font-size: 13px;
        font-weight: 700;
        cursor: pointer;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.12);
      }

      button:disabled {
        cursor: not-allowed;
        opacity: 0.6;
      }

      button.apply {
        border-color: #0066cc;
        background: #0066cc;
        color: #ffffff;
      }

      .processing {
        position: absolute;
        inset: 0;
        display: grid;
        place-items: center;
        background: rgba(255, 255, 255, 0.75);
        color: #17202a;
        font-size: 14px;
        font-weight: 700;
        z-index: 1100;
      }
    `,
  ],
})
export class ImageCropperComponent implements OnChanges, OnDestroy {
  @ViewChild('selector') private selector?: ImageAreaSelectorComponent;

  @Input() src: LuminaSource | null = null;
  @Input() aspectRatio?: number;
  @Input() outputFormat: 'blob' | 'dataUrl' = 'blob';
  @Input() maxWidth = 600;
  @Input() maxHeight = 400;
  @Input() allowReset = true;
  @Input() lineColor = '#0066cc';
  @Input() overlayOpacity = 0.6;
  @Input() buttonPosition:
    | 'top-left'
    | 'top-right'
    | 'top-center'
    | 'bottom-left'
    | 'bottom-center'
    | 'bottom-right' = 'top-left';
  @Input() containerStyle?: Record<string, string | number>;

  @Output() cropChange = new EventEmitter<CropArea>();
  @Output() cropSelectionComplete = new EventEmitter<CropArea>();
  @Output() cropComplete = new EventEmitter<ImageCropperOutput>();
  @Output() processError = new EventEmitter<Error>();
  @Output() resetCrop = new EventEmitter<void>();

  imageSrc?: string;
  appliedPreviewSrc: string | null = null;
  isCropping = false;
  private selectedCrop: CropArea | null = null;
  private objectUrls = new Set<string>();

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['src']) {
      this.revokeGeneratedUrls();
      this.selectedCrop = null;
      this.appliedPreviewSrc = null;
      this.imageSrc = this.resolveImageSrc(this.src);
    }
  }

  ngOnDestroy(): void {
    this.revokeGeneratedUrls();
  }

  handleCropChange(crop: CropArea): void {
    this.selectedCrop = crop;
    this.appliedPreviewSrc = null;
    this.cropChange.emit(crop);
  }

  handleCropComplete(crop: CropArea): void {
    this.selectedCrop = crop;
    this.cropSelectionComplete.emit(crop);
  }

  async applyCrop(): Promise<void> {
    if (
      !this.selectedCrop ||
      this.selectedCrop.width === 0 ||
      this.selectedCrop.height === 0
    ) {
      this.processError.emit(new Error('Please select a crop area'));
      return;
    }

    if (!this.src) {
      this.processError.emit(new Error('No source image provided'));
      return;
    }

    this.isCropping = true;

    try {
      const crop = this.selectedCrop;
      const chain = lumina(this.src).crop(
        crop.x,
        crop.y,
        crop.width,
        crop.height,
      );

      if (this.outputFormat === 'dataUrl') {
        const dataUrl = await chain.toDataURL();
        this.appliedPreviewSrc = dataUrl;
        this.cropComplete.emit(dataUrl);
      } else {
        const blob = await chain.toBlob();
        const previewUrl = URL.createObjectURL(blob);
        this.objectUrls.add(previewUrl);
        this.appliedPreviewSrc = previewUrl;
        this.cropComplete.emit(blob);
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      this.processError.emit(error);
    } finally {
      this.isCropping = false;
    }
  }

  reset(): void {
    this.selectedCrop = null;
    this.appliedPreviewSrc = null;
    this.selector?.reset();
    this.resetCrop.emit();
  }

  private resolveImageSrc(src: LuminaSource | null): string | undefined {
    if (typeof src === 'string') return src;

    if (src instanceof File) {
      const url = URL.createObjectURL(src);
      this.objectUrls.add(url);
      return url;
    }

    return undefined;
  }

  private revokeGeneratedUrls(): void {
    for (const url of this.objectUrls) {
      URL.revokeObjectURL(url);
    }
    this.objectUrls.clear();
  }
}

// src/react/ImageCropper.tsx
import React, { useState, useCallback, useEffect, useMemo } from 'react';
import { lumina } from '../index.js';
import { LuminaCanvas } from './LuminaCanvas';
import { ImageAreaSelector, type CropArea } from './ImageAreaSelector';

export interface ImageCropperProps {
  src: string | File | HTMLImageElement | HTMLCanvasElement | ImageData | null;
  onCropComplete?: (croppedImage: Blob | string) => void;
  onError?: (error: Error) => void;
  aspectRatio?: number;
  outputFormat?: 'blob' | 'dataUrl';
  maxWidth?: number;
  maxHeight?: number;
  showPreview?: boolean;
  allowReset?: boolean;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * ImageCropper - A complete image cropping interface with automatic processing.
 *
 * Combines the `ImageAreaSelector` for interactive crop area selection with
 * `LuminaCanvas` for rendering the applied crop in the same component.
 *
 * @param {ImageCropperProps} props
 * @param {string | File | HTMLImageElement | HTMLCanvasElement | ImageData | null} props.src - Image source
 * @param {Function} [props.onCropComplete] - Callback when crop is finalized (receives Blob or DataURL)
 * @param {Function} [props.onError] - Callback for processing errors
 * @param {number} [props.aspectRatio] - Optional aspect ratio to enforce (width / height)
 * @param {'blob' | 'dataUrl'} [props.outputFormat='blob'] - Output format for cropped image
 * @param {number} [props.maxWidth] - Max width of the container
 * @param {number} [props.maxHeight] - Max height of the container
 * @param {boolean} [props.allowReset=true] - Show reset button after crop is applied.
 * @param {string} [props.className] - CSS class name
 * @param {React.CSSProperties} [props.style] - Inline styles
 *
 * @example
 * ```tsx
 * const handleCropComplete = (croppedBlob: Blob) => {
 *   const url = URL.createObjectURL(croppedBlob);
 *   // Use the cropped image...
 * };
 *
 * <ImageCropper
 *   src="photo.jpg"
 *   aspectRatio={16 / 9}
 *   outputFormat="blob"
 *   onCropComplete={handleCropComplete}
 * />
 * ```
 */
export const ImageCropper: React.FC<ImageCropperProps> = ({
  src,
  onCropComplete,
  onError,
  aspectRatio,
  outputFormat = 'blob',
  maxWidth = 600,
  maxHeight = 400,
  allowReset = true,
  className,
  style,
}) => {
  const [isCropping, setIsCropping] = useState(false);
  const [appliedPreview, setAppliedPreview] = useState<{
    source: ImageCropperProps['src'];
    src: string;
  } | null>(null);
  const appliedPreviewSrc =
    appliedPreview?.source === src ? appliedPreview.src : null;

  // Convert File to URL for ImageAreaSelector
  const imageSrc = useMemo(() => {
    if (typeof src === 'string') return src;
    if (src instanceof File) return URL.createObjectURL(src);
    return undefined;
  }, [src]);

  useEffect(() => {
    return () => {
      if (imageSrc && src instanceof File) {
        URL.revokeObjectURL(imageSrc);
      }
    };
  }, [imageSrc, src]);

  useEffect(() => {
    return () => {
      if (appliedPreview?.src.startsWith('blob:')) {
        URL.revokeObjectURL(appliedPreview.src);
      }
    };
  }, [appliedPreview]);

  const handleCropChange = useCallback(() => {
    setAppliedPreview(null);
  }, []);

  const handleCropComplete = useCallback(
    async (selectedCrop: CropArea) => {
      if (selectedCrop.width === 0 || selectedCrop.height === 0) {
        onError?.(new Error('Please select a crop area'));
        return;
      }

      if (!src) {
        onError?.(new Error('No source image provided'));
        return;
      }

      setIsCropping(true);

      try {
        const chain = lumina(src).crop(
          selectedCrop.x,
          selectedCrop.y,
          selectedCrop.width,
          selectedCrop.height,
        );

        if (outputFormat === 'blob') {
          const blob = await chain.toBlob();
          if (blob) {
            setAppliedPreview({ source: src, src: URL.createObjectURL(blob) });
            onCropComplete?.(blob);
          } else {
            throw new Error('Failed to generate cropped blob.');
          }
        } else {
          const dataUrl = await chain.toDataURL();
          setAppliedPreview({ source: src, src: dataUrl });
          onCropComplete?.(dataUrl);
        }
      } catch (err) {
        const error = err instanceof Error ? err : new Error(String(err));
        onError?.(error);
      } finally {
        setIsCropping(false);
      }
    },
    [onError, onCropComplete, outputFormat, src],
  );

  const handleProcessError = (error: Error) => {
    onError?.(error);
  };

  const handleReset = useCallback(() => {
    setAppliedPreview(null);
  }, []);

  return (
    <div
      className={className}
      style={{
        padding: '16px',
        borderRadius: '8px',
        backgroundColor: '#f5f5f5',
        ...style,
      }}
    >
      <div
        style={{
          position: 'relative',
          maxWidth: maxWidth,
          maxHeight: maxHeight,
          borderRadius: '6px',
          overflow: 'hidden',
          border: '1px solid #ddd',
          backgroundColor: '#fff',
        }}
      >
        {appliedPreviewSrc ? (
          <LuminaCanvas
            source={appliedPreviewSrc}
            style={{
              width: '100%',
              height: '100%',
              display: 'block',
            }}
            onProcessError={handleProcessError}
          />
        ) : (
          imageSrc && (
            <ImageAreaSelector
              src={imageSrc}
              aspect={aspectRatio}
              onCropChange={handleCropChange}
              onCropComplete={handleCropComplete}
              lineColor="#0066cc"
              overlayOpacity={0.6}
            />
          )
        )}

        {isCropping && (
          <div
            style={{
              position: 'absolute',
              inset: 0,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: 'rgba(255, 255, 255, 0.75)',
              color: '#333',
              fontSize: '14px',
              fontWeight: 500,
            }}
          >
            Processing...
          </div>
        )}

        {allowReset && appliedPreviewSrc && !isCropping && (
          <button
            type="button"
            onClick={handleReset}
            style={{
              position: 'absolute',
              top: '12px',
              right: '12px',
              padding: '8px 12px',
              backgroundColor: '#fff',
              color: '#333',
              border: '1px solid #ddd',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '13px',
              fontWeight: 500,
              boxShadow: '0 2px 8px rgba(0, 0, 0, 0.12)',
            }}
          >
            Reset
          </button>
        )}
      </div>
    </div>
  );
};
